{"name":"Dataflow Gen1 sample","description":"","version":"1.0","culture":"en-US","modifiedTime":"2026-01-13T13:21:17.3337909+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"DimStore":{"queryId":"c5da14ad-d52a-4611-ae56-e30150eacbd0","queryName":"DimStore","loadEnabled":true}},"document":"section Section1;\r\nshared DimStore = let\n    Source = Csv.Document(AzureStorage.BlobContents(\"https://larsadlsgen2.blob.core.windows.net/fabric/Store_dimension.csv\"),[Delimiter=\";\", Columns=2, QuoteStyle=QuoteStyle.None]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),\n    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),\n    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"StoreID\", type text}, {\"StoreName\", type text}}),\n    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type1\",\"Location\",\"\",Replacer.ReplaceText,{\"StoreID\"}),\n    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"StoreID\", Int64.Type}})\nin\n    #\"Changed Type2\";\r\n","connectionOverrides":[{"path":"https://larsadlsgen2.blob.core.windows.net/fabric/Store_dimension.csv","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Web\",\"path\":\"https://larsadlsgen2.blob.core.windows.net/fabric/Store_dimension.csv\"}","audience":null},{"path":"https://larsadlsgen2.blob.core.windows.net/fabric/Store_dimension.csv","kind":"AzureBlobs","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"AzureBlobs\",\"path\":\"https://larsadlsgen2.blob.core.windows.net/fabric/Store_dimension.csv\"}","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"DimStore","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DimStore.csv"},"attributes":[{"name":"StoreID","dataType":"int64"},{"name":"StoreName","dataType":"string"}]}]}